import { Link } from "react-router-dom";
import { ArrowRight, Heart, PieChart, Plus, ShieldCheck, Target } from "lucide-react";
import { LogoMark } from "@/shared/ui/logo";

export function FeatureBento() {
  return <section id="recursos" className="mx-auto grid w-full max-w-6xl scroll-mt-24 grid-cols-1 gap-6 px-6 py-20 md:grid-cols-12 md:gap-8 md:py-32">
    <article className="group relative overflow-hidden rounded-[2rem] border bg-white p-8 dark:bg-ink-900 md:col-span-8 md:p-12">
      <div className="max-w-md"><span className="text-[10px] font-bold uppercase tracking-widest text-accent-500 md:text-xs">Inteligência financeira</span><h2 className="mt-4 mb-4 font-display text-3xl font-semibold text-ink-950 dark:text-white md:mb-6 md:text-4xl">Visão 360º das suas finanças.</h2><p className="text-sm leading-relaxed text-muted-500 md:text-base">Contas, cartões, lançamentos e vencimentos organizados em uma linha do tempo simples de acompanhar.</p></div>
      <div className="scrollbar-hidden mt-8 flex gap-4 overflow-x-auto pb-4 md:mt-12 md:overflow-visible md:pb-0">{["Fatura do cartão", "Contas do mês"].map((label, index) => <div key={label} className={`h-56 w-40 shrink-0 rounded-2xl border bg-paper-50 p-4 shadow-sm transition-transform dark:bg-ink-800 md:h-64 md:w-48 ${index ? "md:rotate-6" : "md:-rotate-3"} group-hover:rotate-0`}><div className={`mb-5 h-9 w-9 rounded-lg ${index ? "bg-accent-100" : "bg-coral-100"}`} /><p className="text-xs text-muted-500">{label}</p><div className="mt-2 h-4 w-24 rounded bg-ink-950 dark:bg-paper-50" /><div className="mt-8 space-y-2"><div className="h-2 rounded bg-muted-300/40" /><div className="h-2 w-3/4 rounded bg-muted-300/30" /></div></div>)}</div>
    </article>
    <article className="flex min-h-64 flex-col justify-between rounded-[2rem] bg-accent-500 p-8 text-white md:col-span-4 md:p-12"><div><ShieldCheck className="mb-6 h-9 w-9" /><h3 className="font-display text-2xl font-semibold leading-tight md:text-3xl">Seus dados continuam seus.</h3></div><p className="mt-8 text-sm text-accent-100">O Planejador organiza apenas as informações que você cadastra, sem vender seus dados.</p></article>
    <article className="rounded-[2rem] bg-amber-100 p-8 dark:bg-amber-600/15 md:col-span-4 md:p-12"><h3 className="font-display text-2xl font-semibold text-ink-950 dark:text-white">Metas com progresso claro</h3><p className="mt-4 text-sm text-muted-500">Defina o valor, o prazo e acompanhe quanto falta para chegar lá.</p><Target className="mx-auto mt-8 h-20 w-20 text-amber-500/30" /></article>
    <article className="grid rounded-[2rem] bg-paper-100 p-8 dark:bg-ink-900 md:col-span-8 md:grid-cols-2 md:gap-8 md:p-12"><div className="space-y-6"><div><h3 className="text-sm font-bold">Lançamento rápido</h3><p className="mt-1 text-xs text-muted-500">Registre receitas e despesas com conta, categoria e data.</p></div><div><h3 className="text-sm font-bold">Categorias personalizadas</h3><p className="mt-1 text-xs text-muted-500">Adapte a organização à forma como você realmente vive.</p></div></div><div className="mt-8 flex aspect-video items-center justify-center rounded-xl border bg-white shadow-inner dark:bg-ink-800 md:mt-0"><PieChart className="h-12 w-12 text-accent-500/25" /></div></article>
  </section>;
}

const outcomes = [{ value: "6", label: "áreas integradas", text: "Contas, cartões, lançamentos, metas, fixas e categorias." }, { value: "30d", label: "de visão diária", text: "Acompanhe a evolução recente do saldo em um só gráfico." }, { value: "1", label: "painel central", text: "O contexto que você precisa, sem alternar entre planilhas." }];

export function OutcomeMetrics() {
  return <section id="resultados" className="scroll-mt-24 bg-white py-20 dark:bg-ink-900 md:py-32"><div className="mx-auto max-w-6xl px-6 text-center"><h2 className="mb-12 font-display text-3xl font-semibold tracking-tight md:mb-16 md:text-5xl">Organização que vira clareza</h2><div className="grid gap-12 md:grid-cols-3 md:gap-16">{outcomes.map((item) => <article key={item.label}><p className="tabular text-5xl font-bold tracking-tighter text-accent-500 md:text-6xl">{item.value}</p><h3 className="mt-2 text-lg font-medium">{item.label}</h3><p className="mt-2 text-sm text-muted-500">{item.text}</p></article>)}</div></div></section>;
}

export function UseCases() {
  return <section className="mx-auto max-w-6xl px-6 py-20 md:py-32"><div className="flex flex-col gap-12 md:flex-row md:gap-20"><div className="md:w-1/3"><h2 className="font-display text-3xl font-semibold md:text-4xl">Feito para a vida como ela é</h2><p className="mt-5 leading-relaxed text-muted-500">Comece pequeno e acrescente detalhes à medida que sua rotina financeira evolui.</p></div><div className="grid gap-8 md:w-2/3 md:gap-10"><article className="rounded-2xl border-l-4 border-accent-500 bg-paper-50 p-6 dark:bg-ink-900 md:p-8"><h3 className="font-display text-xl font-semibold">Para sair do improviso</h3><p className="mt-3 text-muted-500">Veja vencimentos próximos e registre movimentos antes que eles virem surpresa.</p></article><article className="rounded-2xl border-l-4 border-amber-500 bg-paper-50 p-6 dark:bg-ink-900 md:p-8"><h3 className="font-display text-xl font-semibold">Para transformar planos em metas</h3><p className="mt-3 text-muted-500">Acompanhe a evolução de cada objetivo sem perder a visão do mês atual.</p></article></div></div></section>;
}

const faqs = [{ q: "Preciso conectar minha conta bancária?", a: "Não. Você cadastra e controla as informações no próprio Planejador, sem fornecer credenciais bancárias." }, { q: "O Planejador é gratuito?", a: "Sim. Você pode criar sua conta e utilizar os recursos disponíveis sem informar cartão de crédito." }, { q: "Posso usar no celular?", a: "Sim. A interface é responsiva e funciona no navegador do computador, tablet ou celular." }];

export function LandingFaq() {
  return <section id="faq" className="mx-auto max-w-6xl scroll-mt-24 border-t px-6 py-20 md:py-32"><h2 className="mb-12 text-center font-display text-3xl font-semibold md:text-4xl">Perguntas frequentes</h2><div className="mx-auto max-w-3xl space-y-4 md:space-y-6">{faqs.map((item) => <details key={item.q} className="glass group cursor-pointer rounded-2xl p-5 md:p-6"><summary className="flex list-none items-center justify-between gap-4 text-sm font-bold md:text-base">{item.q}<Plus className="h-5 w-5 shrink-0 transition-transform group-open:rotate-45" /></summary><p className="mt-4 text-sm leading-relaxed text-muted-500">{item.a}</p></details>)}</div></section>;
}

export function FinalCta() {
  return <section className="mx-auto max-w-6xl px-4 py-20 md:px-6 md:py-32"><div className="relative overflow-hidden rounded-[2rem] bg-ink-950 p-10 text-center text-white md:rounded-[3rem] md:p-24"><div className="relative z-10"><h2 className="font-display text-4xl font-semibold tracking-tighter md:text-7xl">Pronto para ter clareza?</h2><p className="mx-auto mt-6 mb-10 max-w-2xl text-lg text-muted-300 md:mt-8 md:mb-12 md:text-xl">Comece sua organização financeira hoje. Sem cartão de crédito e sem complicação.</p><Link to="/registro" className="inline-flex h-14 items-center gap-3 rounded-2xl bg-accent-500 px-8 font-bold transition-transform hover:bg-accent-400 active:scale-95 md:h-16 md:px-10 md:text-lg">Criar conta gratuita<ArrowRight className="h-5 w-5" /></Link></div><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(38,163,124,.18),transparent_40%),radial-gradient(circle_at_80%_80%,rgba(229,72,77,.12),transparent_40%)]" /></div></section>;
}

export function LandingFooter() {
  return <footer className="bg-ink-950 pt-16 pb-12 text-paper-100 md:pt-24"><div className="mx-auto grid max-w-6xl gap-10 px-6 sm:grid-cols-2 md:gap-12 lg:grid-cols-4"><div className="sm:col-span-2"><Link to="/" className="mb-6 flex items-center gap-2.5 font-display text-xl font-semibold text-white"><LogoMark className="h-9 w-9" />Planejador</Link><p className="max-w-sm text-sm leading-relaxed text-muted-300">Organização financeira pessoal para enxergar o mês, planejar metas e tomar decisões com mais calma.</p></div><div><h3 className="mb-5 text-xs font-bold uppercase tracking-widest text-white">Produto</h3><ul className="space-y-4 text-sm text-muted-300"><li><a href="#recursos">Recursos</a></li><li><a href="#resultados">Resultados</a></li><li><a href="#faq">Privacidade e FAQ</a></li></ul></div><div><h3 className="mb-5 text-xs font-bold uppercase tracking-widest text-white">Acesso</h3><ul className="space-y-4 text-sm text-muted-300"><li><Link to="/login">Entrar</Link></li><li><Link to="/registro">Criar conta</Link></li></ul></div></div><div className="mx-auto mt-16 flex max-w-6xl flex-col items-center justify-between gap-4 border-t border-ink-800 px-6 pt-10 text-[11px] uppercase tracking-widest text-muted-500 md:flex-row"><span>© {new Date().getFullYear()} Planejador Financeiro</span><span className="flex items-center gap-1">Feito com <Heart className="h-3 w-3 text-coral-500" /> para sua tranquilidade</span></div></footer>;
}
